"""initial schema

Revision ID: a5c147fbc8b9
Revises: 
Create Date: 2026-10-09 23:08:15.870161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c147fbc8b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_size', sa.BigInteger(), nullable=False),
    sa.Column('stored_size', sa.BigInteger(), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blobs_sha256'), ['sha256'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('blob_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_token_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['blobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_blob_id'), ['blob_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_public_id'))
        batch_op.drop_index(batch_op.f('ix_files_blob_id'))

    op.drop_table('files')
    with op.batch_alter_table('blobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blobs_sha256'))

    op.drop_table('blobs')
    # ### end Alembic commands ###
